#!/usr/bin/env bash
#Transfer file to a server

# Check if the correct number of parameter passed
if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Initialize some parameters
file="$1"
ip="$2"
user_name="$3"

if [ $# -ge 4 ]; then
	key_file="$4"
	scp -o StrictHostKeyChecking=no -i $key_file $file $user_name@$ip:~/
else
	# Transfer the file to the server
	scp -o StrictHostKeyChecking=no $file $user_name@$ip:~/
fi
