#!/usr/bin/env bash
# Configuring a new server

# Update the apt packaging syste
apt-get -y update

# Install nginx
apt-get -y install nginx

# Create an index page
echo "Hello World!" > /var/www/html/index.html

# Server configuration
echo "server {
        listen  80 default_server;
        listen  [::]:80 default_server;

        root    /var/www/html;
        index   index.html index.htm;

	server_name _;

	location / {
		try_files \$uri \$uri/ =404
	}

}" > /etc/nginx/sites-available/default

# Allow  http
ufw allow 'Nginx HTTP'

# Enable ufw
ufw -y enable

# Reload
nginx -s reload

# Start servic
service nginx start

# Get the content
curl localhost
