#!/usr/bin/env bash
# Setup Nginx server

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
hostname=$(hostname)
sudo sed -i "/listen 80 default_server/a add_header X-Served-By $hostname;" /etc/nginx/sites-available/default
sudo systemctl restart nginx

