#!/usr/bin/env bash
# do some work :)

my_exit() {
	rm /var/run/myscript.pid
	exit
}

trap 'echo "Y U no love me?!"; exit' SIGINT
trap 'echo "I hate the kill command"; my_exit' SIGTERM
trap 'my_exit' SIGQUIT

echo $$ > /var/run/myscript.pid

while (( 1 ))
do
	echo "To infinity and beyond"
	sleep 2
done
