#!/usr/bin/env bash
# Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed.

content=$(ls)

for name in $content
do
	echo "$name" | cut -d '-' -f 2
done
