#!/usr/bin/env bash
# Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed.

content=$(find . -maxdepth 1 -type f ! -name ".*" | cut -sd '-' -f 2)

echo "$content"
